name: build additional packages

on: 
  workflow_dispatch:
  # push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Source Code
      uses: actions/checkout@v3
    - name: build
      run: |
        sudo curl -sSL https://raw.githubusercontent.com/ros/rosdistro/master/ros.key -o /usr/share/keyrings/ros-archive-keyring.gpg
        echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/ros-archive-keyring.gpg] http://packages.ros.org/ros2/ubuntu $(. /etc/os-release && echo $UBUNTU_CODENAME) main" | sudo tee /etc/apt/sources.list.d/ros2.list > /dev/null
        sudo apt update
        sudo apt install -y tree python3-vcstool
        mkdir -p src
        vcs import src < addition.repos
        python3 get_package_path.py
        num=$(cat packages-path.txt | wc -l)
        echo "packages number total: ${num}"
        mkdir deb
        docker run --rm -v ${PWD}:/root/ros_humble kaylor/focal_humble_env:latest sh -c "cd /root/ros_humble && bash ./build_focal_humble_env.sh"
        tree deb
    
    - name: sync files
      uses: burnett01/rsync-deployments@6.0.0
      with:
        switches: -avzr
        path: deb/
        remote_path: ~/addition_deb
        remote_host: ${{ secrets.HOST }}
        remote_user: ${{ secrets.USERNAME }}
        remote_key: ${{ secrets.SSH_KEY }}
        remote_port: ${{ secrets.PORT }}
  
    - name: Aptly release
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.SSH_KEY }}
        port: ${{ secrets.PORT }}
        script: |
          aptly repo add ros2_humble_focal addition_deb/*
          aptly publish update -batch -passphrase="${{ secrets.GPG_PASSPHRASE}}" focal ros2_humble_focal 



