name: build ros2 release packages

env:
  PKG: build-release
  DOCKER_IMG: kaylor/focal_humble_env:v1.1
on: 
  workflow_dispatch:
  push:
    paths:
      - ".github/workflows/build-release.yml"
  

jobs:
  prepare:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Source Code
      uses: actions/checkout@v3
    
    - name: Prepare
      run: |
        sudo curl -sSL https://raw.githubusercontent.com/ros/rosdistro/master/ros.key -o /usr/share/keyrings/ros-archive-keyring.gpg
        echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/ros-archive-keyring.gpg] http://packages.ros.org/ros2/ubuntu $(. /etc/os-release && echo $UBUNTU_CODENAME) main" | sudo tee /etc/apt/sources.list.d/ros2.list > /dev/null
        sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys DE86F73ED9E67D5E
        echo "deb [arch=amd64] http://42.194.233.81:60000/ros2_humble_focal focal main" | sudo tee /etc/apt/sources.list.d/kaylor-ros2.list > /dev/null
        sudo apt update
        ./check_package.py --cfg user.repos
        cat updates.repos
        sudo apt install -y tree python3-vcstool
        mkdir -p src
        vcs import src < updates.repos
        python3 get_package_path.py
        num=$(cat packages-path.txt | wc -l)
        echo "packages number total: ${num}"

    - name: upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: all
        path: ./
    
  build:
    runs-on: ubuntu-latest
    needs: [prepare]
    strategy:
      matrix:
        index: [ 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20 ]
    steps:
      - name: download artifact
        uses: actions/download-artifact@v3

      - name: build
        run: |
          ls -R all/
          cd all/





    # - name: build
    #   run: |
    #     git clone https://github.com/ros2-gbp/${PKG}.git -b ${{ matrix.branch }} --depth 1
    #     sed -i 's/jammy/focal/g' ${PKG}/debian/changelog
    #     cat ${PKG}/debian/changelog
    #     sed -i 's|dh_shlibdeps |dh_shlibdeps --dpkg-shlibdeps-params=--ignore-missing-info |' ${PKG}/debian/rules
    #     cat ${PKG}/debian/rules
    #     docker run --rm -v ${PWD}/${PKG}:/root/src/${PKG} kaylor/focal_humble_env:v1.1 sh -c "cd /root/src/${PKG} && fakeroot debian/rules binary && mkdir deb && mv ../ros-* deb/"
    #     ls -alR ${PKG}/deb
      
    # - name: sync files
    #   uses: burnett01/rsync-deployments@6.0.0
    #   with:
    #     switches: -avzr
    #     path: ${PKG}/deb/
    #     remote_path: ~/github/${PKG}
    #     remote_host: ${{ secrets.HOST }}
    #     remote_user: ${{ secrets.USERNAME }}
    #     remote_key: ${{ secrets.SSH_KEY }}
    #     remote_port: ${{ secrets.PORT }}
  
    # - name: Aptly release
    #   uses: appleboy/ssh-action@v1.0.0
    #   with:
    #     host: ${{ secrets.HOST }}
    #     username: ${{ secrets.USERNAME }}
    #     key: ${{ secrets.SSH_KEY }}
    #     port: ${{ secrets.PORT }}
    #     script: |
    #       aptly repo add ros2_humble_focal github/*
    #       aptly publish update -batch -passphrase="${{ secrets.GPG_PASSPHRASE}}" focal ros2_humble_focal 
