name: build ros2 release packages

env:
  PKG: build-release
  # DOCKER_IMG: kaylor/focal_humble_env:v1.1
  DOCKER_IMG: kaylor/ubuntu2004_humble:latest
on: 
  workflow_dispatch:
  push:
    paths:
      - ".github/workflows/build-release.yml"
      - "user.repos"
  

jobs:
  prepare:
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout Source Code
      uses: actions/checkout@v3
    
    - name: Prepare
      run: |
        sudo curl -sSL https://raw.githubusercontent.com/ros/rosdistro/master/ros.key -o /usr/share/keyrings/ros-archive-keyring.gpg
        echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/ros-archive-keyring.gpg] http://packages.ros.org/ros2/ubuntu $(. /etc/os-release && echo $UBUNTU_CODENAME) main" | sudo tee /etc/apt/sources.list.d/ros2.list > /dev/null
        sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys DE86F73ED9E67D5E
        echo "deb [arch=amd64] http://42.194.233.81:60000/ros2_humble_focal focal main" | sudo tee /etc/apt/sources.list.d/kaylor-ros2.list > /dev/null
        sudo apt update
        sudo apt install -y tree python3-vcstool python3-apt
        ./check_package.py --cfg user.repos
        cat updates.repos
        echo "*********************"
        # mkdir -p src
        # vcs import src < updates.repos
        # python3 get_package_path.py
        # num=$(cat packages-path.txt | wc -l)
        # echo "packages number total: ${num}"
        ls -al

    - name: upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: all
        path: ./
    
  build:
    runs-on: ubuntu-latest
    needs: [prepare]
    strategy:
      matrix:
        index: [ 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20 ]
    steps:
      - name: download artifact
        uses: actions/download-artifact@v3

      - name: build
        run: |
          lsb_release -a
          cd all/
          ls -R
          # if [ -f packages-path.txt${{ matrix.index }} ]; then
          #   mkdir -p deb
          #   num=$(cat packages-path.txt${{ matrix.index }} | wc -l)
          #   echo "new packages number total: ${num}"
          #   echo "job${{ matrix.index }} has ${num} packages" > deb/job${{ matrix.index }}.txt
          #   docker run --rm -v ${PWD}:/root/ros_humble ${DOCKER_IMG} sh -c "cd /root/ros_humble && bash ./build_focal_humble_env.sh packages-path.txt${{ matrix.index }}"
          #   tree deb
          # else
          #   echo "packages-path.txt${{ matrix.index }}: no such this file"
          #   mkdir -pv deb
          #   touch deb/build${{ matrix.index }}.txt
          # fi
      
      - name: sync files
        uses: burnett01/rsync-deployments@6.0.0
        with:
          switches: -avzr
          path: all/deb/
          remote_path: ~/github/release
          remote_host: ${{ secrets.HOST }}
          remote_user: ${{ secrets.USERNAME }}
          remote_key: ${{ secrets.SSH_KEY }}
          remote_port: ${{ secrets.PORT }}
  
      - name: Aptly release
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.PORT }}
          script: |
            aptly repo add ros2_humble_focal github/*
            aptly publish update -batch -passphrase="${{ secrets.GPG_PASSPHRASE}}" focal ros2_humble_focal 
