name: build ros2 humble deb pkg for ubuntu2004-amd64

env:
  CHANGELOG_AUTHOR_NAME: "Kaylor"
  CHANGELOG_AUTHOR_EMAIL: "kaylor.chen@qq.com"

on:
  push:
    branches:
    - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Source Code
      uses: actions/checkout@v3

    - name: Build 
      run: |
        sudo curl -sSL https://raw.githubusercontent.com/ros/rosdistro/master/ros.key -o /usr/share/keyrings/ros-archive-keyring.gpg
        echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/ros-archive-keyring.gpg] http://packages.ros.org/ros2/ubuntu $(. /etc/os-release && echo $UBUNTU_CODENAME) main" | sudo tee /etc/apt/sources.list.d/ros2.list > /dev/null
        sudo apt update
        sudo apt install -y tree python3-vcstool
        mkdir -p src
        # vcs import --input https://raw.githubusercontent.com/ros2/ros2/humble/ros2.repos src
        vcs import src << user.repos
        tree src

    
    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: all_pkgs
        path: ./deb/
