name: build teleop twist

env:
  CHANGELOG_AUTHOR_NAME: "Kaylor"
  CHANGELOG_AUTHOR_EMAIL: "kaylor.chen@qq.com"

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: ssh test
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.SSH_KEY }}
        port: ${{ secrets.PORT }}
        script: ll ~/



