name: build ros_workspace-release repository

env:
  PKG: ros_workspace-release
on: 
  workflow_dispatch:
  push:
    paths:
      - ".github/workflows/ros_workspace-release.yml"
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        branch: [ debian/ros-humble-ros-workspace_1.0.2-2_jammy ]
        architecture: [amd64, arm64]
    steps:
    - name: build
      run: |
        git clone https://github.com/ros2-gbp/${PKG}.git -b ${{ matrix.branch }} --depth 1
        sed -i 's/jammy/focal/g' ${PKG}/debian/changelog
        cat ${PKG}/debian/changelog
        sed -i 's|dh_shlibdeps |dh_shlibdeps --dpkg-shlibdeps-params=--ignore-missing-info |' ${PKG}/debian/rules
        cat ${PKG}/debian/rules
        sed -i '/Conflicts/d' ${PKG}/debian/control
        cat ${PKG}/debian/control
        if [ ${{ matrix.architecture}} == arm64 ]; then
          echo Architecture is ${{ matrix.architecture}}
          docker run --privileged --rm tonistiigi/binfmt --install all
        fi
        docker pull --platform=linux/${{ matrix.architecture}} kaylor/focal_humble_env:latest
        docker run --rm -v ${PWD}/${PKG}:/root/src/${PKG} kaylor/focal_humble_env:latest sh -c "cd /root/src/${PKG} && DEB_BUILD_OPTIONS="parallel=2 nocheck" fakeroot debian/rules binary && mkdir deb && mv ../ros-humble-* deb/"
        ls -alR ${PKG}/deb
      
    - name: sync files
      uses: burnett01/rsync-deployments@6.0.0
      with:
        switches: -avzr
        path: ${PKG}/deb/
        remote_path: ~/deb/${{ matrix.architecture }}/new_humble
        remote_host: ${{ secrets.HOST }}
        remote_user: ${{ secrets.USERNAME }}
        remote_key: ${{ secrets.SSH_KEY }}
        remote_port: ${{ secrets.PORT }}
  
    - name: Aptly release
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.SSH_KEY }}
        port: ${{ secrets.PORT }}
        script: |
          aptly repo add ros2_humble_focal deb/${{ matrix.architecture }}/new_humble
          aptly publish update  --force-overwrite  -batch -passphrase="${{ secrets.GPG_PASSPHRASE}}" focal ros2/ubuntu 
          ls deb/${{ matrix.architecture }}/new_humble/*deb > /dev/null 2>&1
          if [ $? != "0" ]; then
            echo "there are not debian packages"
          else
            mv deb/${{ matrix.architecture }}/new_humble/*deb deb/${{ matrix.architecture }}/humble
          fi
